# Render Blueprint for Easy Backend Deployment
services:
  - type: web
    name: coffeeshop-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /api/health
    
databases:
  - name: coffeeshop-mongodb
    databaseName: coffeeshop
    user: coffeeshop_user
