name: Deploy Backend to AWS App Runner

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
      - '.github/workflows/aws-backend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to AWS App Runner
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file aws-backend-infrastructure.yaml \
          --stack-name coffeeshop-backend \
          --parameter-overrides \
            MongoDBConnectionString="${{ secrets.MONGODB_URI }}" \
            JWTSecret="${{ secrets.JWT_SECRET }}" \
            GoogleClientId="${{ secrets.GOOGLE_CLIENT_ID }}" \
            GoogleClientSecret="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          --capabilities CAPABILITY_IAM

    - name: Get Backend URL
      id: backend-url
      run: |
        BACKEND_URL=$(aws cloudformation describe-stacks \
          --stack-name coffeeshop-backend \
          --query 'Stacks[0].Outputs[?OutputKey==`BackendServiceURL`].OutputValue' \
          --output text)
        echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
        echo "Backend URL: $BACKEND_URL"

    - name: Comment Backend URL on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 Backend deployed successfully!\n\n**Backend URL:** ${{ steps.backend-url.outputs.url }}\n**Health Check:** ${{ steps.backend-url.outputs.url }}/api/health`
          });
